version: '3'
services:
  informix-server:
      image: "ibmcom/informix-developer-database"
      container_name: "informix"
      hostname: "informix"
      environment:
          LICENSE: 'accept'
          SIZE:    'small'
          RUN_FILE_POST_INIT: timeseries_generic.sh
      ports:
         - 27018:27018
      volumes: 
         - ${PWD}/informix-server:/opt/ibm/config
  data-generator:
      image: "python:3.6-alpine"
      depends_on: 
          - message-broker
          - data-reader 
      container_name: "datagen"
      hostname: "datagen"
      volumes: 
         - ${PWD}/data-generator:/usr/src/myapp
      working_dir: /usr/src/myapp
      environment:
          BROKER: 'msgbroker'
          BROKER_PORT: 1883
          BROKER_TOPIC: 'datagen/datagen1'
      entrypoint: python datagen.py     
  data-reader:
      image: "python:3.6-alpine"
      depends_on: 
         - message-broker
      container_name: "datareader"
      hostname: "datareader"
      volumes: 
         - ${PWD}/data-reader:/usr/src/myapp
      working_dir: /usr/src/myapp
      environment:
          BROKER: 'msgbroker'
          BROKER_PORT: 1883
          BROKER_TOPIC: 'datagen/datagen1'
          REST_ENDPOINT: 'http://informix:27018/tsdb/tstab_v'
      entrypoint: python datareader.py     
  message-broker:
      image: "eclipse-mosquitto"
      depends_on: 
         - informix-server 
      container_name: "msgbroker"
      hostname: "msgbroker"
  grafana-ui:
      image: "grafana/grafana"
      depends_on: 
         - informix-server 
      ports:
         - 3000:3000
      container_name: "grafana"
      hostname: "grafana"
      volumes: 
        - ${PWD}/grafana/plugins:/var/lib/grafana/plugins
        - ${PWD}/grafana/provisioning:/etc/grafana/provisioning



